restart.include.awssdk-dynamodb=/dynamodb-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-enhanced=/dynamodb-enhanced-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-core=/sdk-core-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-aws-core=/aws-core-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-regions=/regions-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-auth=/auth-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-utils=/utils-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-annotations=/annotations-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-profiles=/profiles-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-json=/json-utils-[\\w\\d-\\.]+\\.jar
restart.include.awssdk-endpoints=/endpoints-spi-[\\w\\d-\\.]+\\.jar
